services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /Users/gregoire/Desktop/ytrack/integration/cours1/jenkins:/var/jenkins_home
    restart: unless-stopped
    user: root
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
