services:
  jenkins-agent-python:
    image: jenkins-agent-python:latest
    container_name: jenkins-agent-python
    restart: unless-stopped
    user: root
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=docker-agent-python
      - JENKINS_SECRET=b3b04952b61b8f8169f04ca0ed99a74ab3ed99dc69d5e44709eb4cd7c7c9436f
      - JENKINS_AGENT_WORKDIR=/home/jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
  pytest-agent:
    image: pytest-agent:latest
    container_name: agent-python-test
    restart: unless-stopped
    user: root
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent-python-test
      - JENKINS_SECRET=9cc5f79a811ce14001fa4add219202d1b27b8b6261e494fe8f1fd2f7a90d90eb
      - JENKINS_AGENT_WORKDIR=/home/jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /Users/gregoire/Desktop/ytrack/integration/cours1/jenkins:/var/jenkins_home
    restart: unless-stopped
    user: root
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - /Users/gregoire/docker/sonarqube_data:/opt/sonarqube/data
      - /Users/gregoire/docker/sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_SEARCH_JAVA_OPTS=-Xms1G -Xmx1G
    depends_on:
      - sonar-db

  sonar-db:
    image: postgres:13
    container_name: sonar-db
    volumes:
      - /Users/gregoire/docker/sonar-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    restart: unless-stopped

